changelog:
  categories:
  - title: Breaking Changes
    labels:
    - Semver-Major
    - breaking
  - title: Features 
    labels:
    - Semver-Minor
    - feat
  - title: Bug fixes 
    labels:
    - Semver-Patch
    - bug
  - title: Other Changes
    labels:
       - “*”
